<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GrpcServices\Test;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad010a0a746573742e70726f746f12087365727669636573221a0a0b50696e674d657373616765120b0a036d7367180120012809323e0a045465737412360a0450696e6712152e73657276696365732e50696e674d6573736167651a152e73657276696365732e50696e674d65737361676522004231ca021a4772706353657276696365735c546573745c4d65737361676573e202114772706353657276696365735c54657374620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

