<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GrpcServices\User\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.UserMessage</code>
 */
class UserMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int32 city_id = 2;</code>
     */
    protected $city_id = 0;
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string last_name = 4;</code>
     */
    protected $last_name = '';
    /**
     * Generated from protobuf field <code>string sur_name = 5;</code>
     */
    protected $sur_name = '';
    /**
     * Generated from protobuf field <code>bool is_active = 6;</code>
     */
    protected $is_active = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int $city_id
     *     @type string $name
     *     @type string $last_name
     *     @type string $sur_name
     *     @type bool $is_active
     * }
     */
    public function __construct($data = NULL) {
        \GrpcServices\User\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 city_id = 2;</code>
     * @return int
     */
    public function getCityId()
    {
        return $this->city_id;
    }

    /**
     * Generated from protobuf field <code>int32 city_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCityId($var)
    {
        GPBUtil::checkInt32($var);
        $this->city_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_name = 4;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Generated from protobuf field <code>string last_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sur_name = 5;</code>
     * @return string
     */
    public function getSurName()
    {
        return $this->sur_name;
    }

    /**
     * Generated from protobuf field <code>string sur_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSurName($var)
    {
        GPBUtil::checkString($var, True);
        $this->sur_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_active = 6;</code>
     * @return bool
     */
    public function getIsActive()
    {
        return $this->is_active;
    }

    /**
     * Generated from protobuf field <code>bool is_active = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsActive($var)
    {
        GPBUtil::checkBool($var);
        $this->is_active = $var;

        return $this;
    }

}

